# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.0.4
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: 06a36657-6b65-4e0b-bbb9-89820fb5cfe5
          # Email that you use with heroku
          heroku_email: kim.david.j@gmail.com
          # The appname to use for deploying/updating
          heroku_app_name: brewery-buddy-frontend
          # An optional buildpack to use when creating the heroku application
          buildpack: nodejs
          # The branch that you would like to deploy to Heroku
          branch: master
